### ISSUE TITLE
SQLite Database keeps locking

### ISSUE THREAD

**Issue by zacwm** [nichogx/DiscordRoleSync#3]
There is currently an issue where the database can lock itself and unable to edit when adding new users, even after a server restart.
I'm unsure how to fix this...
```
[14:11:28] [JDA MainWS-ReadThread/ERROR]: [DiscordRoleSync] An error occurred while trying to check roles for the user. Please check the stack trace below and contact the developer.
[14:11:28] [JDA MainWS-ReadThread/WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1010)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:1022)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at org.sqlite.core.DB.execute(DB.java:861)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at dev.nicho.rolesync.db.DatabaseHandler.addToWhitelist(DatabaseHandler.java:143)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at dev.nicho.rolesync.SyncBot.checkMemberRoles(SyncBot.java:191)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at dev.nicho.rolesync.SyncBot.lambda$null$0(SyncBot.java:71)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.requests.DeferredRestAction.queue(DeferredRestAction.java:126)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at dev.nicho.rolesync.SyncBot.lambda$onReady$2(SyncBot.java:64)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at dev.nicho.rolesync.db.DatabaseHandler.forAllLinkedUsers(DatabaseHandler.java:206)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at dev.nicho.rolesync.SyncBot.onReady(SyncBot.java:62)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:376)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:166)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.requests.WebSocketClient.ready(WebSocketClient.java:198)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.handle.GuildSetupController.ready(GuildSetupController.java:103)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.handle.GuildSetupNode.completeSetup(GuildSetupNode.java:383)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.handle.GuildSetupNode.handleMemberChunk(GuildSetupNode.java:266)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.handle.GuildSetupController.onMemberChunk(GuildSetupController.java:221)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.handle.GuildMembersChunkHandler.handleInternally(GuildMembersChunkHandler.java:56)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:905)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:792)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:770)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:943)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[14:11:28] [JDA MainWS-ReadThread/WARN]: 	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by nichogx** [comment]
Do you have any steps to reproduce the error? 

Also, are you using any plugin management thing such as plugman? Those are NOT supported and should not be used. If you need to restart the plugin you should restart the server.

**Comment by zacwm** [comment]
I'm not using any plugin manager. My current steps to reproduce the error is to just start the server, I believe it is still reading as it is letting already linked users join, however when a new user is trying to link, it throws this error.

**Comment by nichogx** [comment]
Can't reproduce. The DB file being locked usually means another process/thread is writing to it. Deleting the database.db file would certainly fix it but you would lose the linked information. If you don't want to do that try joining the Discord server to get support.

**Comment by zacwm** [comment]
I've started a fresh `database.db` by deleting the locked one.

There was no process/thread writing to it. This does explain the issue as the server had a power outage causing the database along with the world to be locked (worlds resolved by deleting the `session.lock` file).
Unsure if there is a possible fix for this with your plugin though. Sorry for the issue.
