### ISSUE TITLE
Not fully whitelisting players

### ISSUE THREAD

**Issue by edeuss** [nichogx/DiscordRoleSync#7]
Give the role to the player but doesn't white list them. (It whitelisted players for a bit but then stopped).

```
03.04 09:27:54 [Server] ERROR [net.dv8tion.jda.internal.requests.WebSocketClient] There was an error in the WebSocket connection
03.04 09:27:54 [Server] INFO java.lang.BootstrapMethodError: java.lang.IllegalStateException: zip file closed
03.04 09:27:54 [Server] INFO at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:1099) ~[?:?]
03.04 09:27:54 [Server] INFO at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:1067) ~[?:?]
03.04 09:27:54 [Server] INFO at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:59) ~[?:?]
03.04 09:27:54 [Server] INFO at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
03.04 09:27:54 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:905) ~[?:?]
03.04 09:27:54 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:792) ~[?:?]
03.04 09:27:54 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:770) ~[?:?]
03.04 09:27:54 [Server] INFO at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:943) ~[?:?]
03.04 09:27:54 [Server] INFO at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
03.04 09:27:54 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
03.04 09:27:54 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
03.04 09:27:54 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
03.04 09:27:54 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
03.04 09:27:54 [Server] INFO at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
03.04 09:27:54 [Server] INFO at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
03.04 09:27:54 [Server] INFO Caused by: java.lang.IllegalStateException: zip file closed
03.04 09:27:54 [Server] INFO at java.util.zip.ZipFile.ensureOpen(ZipFile.java:915) ~[?:?]
03.04 09:27:54 [Server] INFO at java.util.zip.ZipFile.getEntry(ZipFile.java:347) ~[?:?]
03.04 09:27:54 [Server] INFO at java.util.zip.ZipFile$1.getEntry(ZipFile.java:1121) ~[?:?]
03.04 09:27:54 [Server] INFO at java.util.jar.JarFile.getEntry0(JarFile.java:578) ~[?:?]
03.04 09:27:54 [Server] INFO at java.util.jar.JarFile.getEntry(JarFile.java:508) ~[?:?]
03.04 09:27:54 [Server] INFO at java.util.jar.JarFile.getJarEntry(JarFile.java:470) ~[?:?]
03.04 09:27:54 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:144) ~[patched_1.16.5.jar:git-Paper-576]
03.04 09:27:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.5.jar:git-Paper-576]
03.04 09:27:54 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.5.jar:git-Paper-576]
03.04 09:27:54 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-576]
03.04 09:27:54 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
03.04 09:27:54 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
03.04 09:27:54 [Server] INFO ... 15 more
```

**Comment by nichogx** [comment]
Sorry, I need more description than that to try to find the problem. Please join the Discord so we can work on your problem :)
